# refer to: https://github.com/bitnami/bitnami-docker-moodle
# image: https://hub.docker.com/r/bitnami/moodle

version: "3.8"


version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:${DB_MARIADB_VERSION}
    environment:
      - MARIADB_USER=${DB_MARIADB_USER}
      - MARIADB_PASSWORD=${DB_MARIADB_PASSWORD}
      - MARIADB_DATABASE=${DB_MARIADB_NAME}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb
  
  moodle:
    image: docker.io/bitnami/moodle:4
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb

volumes:
  mariadb_data:
  moodle_data:
  moodledata_data:

networks:
  default:
      name: "${APP_NAME}"
